# Generated by Django 5.2.7 on 2026-02-21 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(max_length=50)),
                ('platform_user_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, max_length=50)),
                ('scope', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('followers_count', models.BigIntegerField(default=0)),
                ('subscribers_count', models.BigIntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_count', models.IntegerField(default=1)),
                ('usage_date', models.DateField(auto_now_add=True)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to='platforms.platformaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=255)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('payload_json', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('platform_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='platforms.platformaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
