# Generated by Django 5.2.7 on 2026-04-04 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_workspaceinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('app_name', models.CharField(max_length=255)),
                ('platform', models.CharField(default='instagram', max_length=50)),
                ('app_id', models.CharField(max_length=255)),
                ('app_secret', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('profile_picture_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('psid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('developer_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_accounts', to='platforms.developerapp')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(max_length=50)),
                ('account_type', models.CharField(blank=True, choices=[('facebook_user', 'Facebook User'), ('instagram_business', 'Instagram Business'), ('facebook_page', 'Facebook Page'), ('whatsapp_business', 'WhatsApp Business')], max_length=50, null=True)),
                ('meta_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_parent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('platform_user_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, max_length=50)),
                ('scope', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('followers_count', models.BigIntegerField(default=0)),
                ('follows_count', models.BigIntegerField(default=0)),
                ('media_count', models.BigIntegerField(default=0)),
                ('subscribers_count', models.BigIntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='platforms.platformaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to='workspaces.workspace')),
            ],
            options={
                'unique_together': {('platform_user_id', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_count', models.IntegerField(default=1)),
                ('usage_date', models.DateField(auto_now_add=True)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to='platforms.platformaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('image', 'Image'), ('reel', 'Reel'), ('story', 'Story'), ('video', 'Video')], max_length=10)),
                ('template_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.template')),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=255)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('payload_json', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('platform_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='platforms.platformaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountTemplateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('image', 'Image'), ('reel', 'Reel'), ('story', 'Story'), ('video', 'Video')], max_length=10)),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_configurations', to='platforms.developerappaccount')),
            ],
            options={
                'unique_together': {('account', 'template_type')},
            },
        ),
        migrations.CreateModel(
            name='AccountTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('image', 'Image'), ('reel', 'Reel'), ('story', 'Story'), ('video', 'Video')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_templates', to='platforms.developerappaccount')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.template')),
            ],
            options={
                'unique_together': {('account', 'template_type')},
            },
        ),
    ]
