# Generated by Django 5.2.7 on 2026-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerappaccount',
            name='followers_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developerappaccount',
            name='follows_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='developerappaccount',
            name='media_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
