# Generated by Django 5.2.7 on 2026-02-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('instagram_business', 'Instagram Business'), ('facebook_page', 'Facebook Page')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='external_parent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='external_parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='meta_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
