# Generated by Django 5.2.7 on 2026-02-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_platformaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='platforms.platformaccount'),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('instagram_business', 'Instagram Business'), ('facebook_page', 'Facebook Page'), ('whatsapp_business', 'WhatsApp Business')], max_length=50, null=True),
        ),
    ]
