# Generated by Django 5.2.7 on 2026-04-13 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_developerappaccount_followers_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='developerappaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='developerappaccount',
            name='developer_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_accounts', to='platforms.developerapp'),
        ),
    ]
