# Generated by Django 5.2.7 on 2026-04-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_developerappaccount_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerappaccount',
            name='developer_app',
        ),
        migrations.DeleteModel(
            name='DeveloperApp',
        ),
    ]
