# Generated by Django 5.2.7 on 2026-02-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_platformaccount_parent_account_and_more'),
        ('workspaces', '0003_workspaceinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('facebook_user', 'Facebook User'), ('instagram_business', 'Instagram Business'), ('facebook_page', 'Facebook Page'), ('whatsapp_business', 'WhatsApp Business')], max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='platformaccount',
            constraint=models.UniqueConstraint(fields=('workspace', 'platform', 'platform_user_id'), name='unique_platform_account'),
        ),
    ]
