# Generated by Django 5.2.7 on 2026-02-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_alter_platformaccount_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='platformaccount',
            name='unique_platform_account',
        ),
        migrations.AlterUniqueTogether(
            name='platformaccount',
            unique_together={('platform_user_id', 'platform')},
        ),
    ]
