# Generated by Django 5.2.7 on 2026-03-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_remove_platformaccount_unique_platform_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='follows_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='media_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
