# Generated by Django 5.2.7 on 2026-03-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_platformaccount_follows_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformaccount',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_accounts', to='platforms.platformaccount'),
        ),
    ]
