# Generated by Django 5.2.7 on 2026-03-22 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0007_alter_platformaccount_parent_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformaccount',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='platforms.platformaccount'),
        ),
        migrations.CreateModel(
            name='DeveloperApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('app_name', models.CharField(max_length=255)),
                ('platform', models.CharField(default='instagram', max_length=50)),
                ('app_id', models.CharField(max_length=255)),
                ('app_secret', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('developer_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_accounts', to='platforms.developerapp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
