# Generated by Django 5.2.7 on 2026-03-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0008_alter_platformaccount_parent_account_developerapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerappaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
