# Generated by Django 5.2.7 on 2026-03-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0009_developerappaccount_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerappaccount',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developerappaccount',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developerappaccount',
            name='psid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='developerappaccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
