# Generated by Django 5.2.7 on 2026-03-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0010_developerappaccount_is_flagged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerappaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
