# Generated by Django 5.2.7 on 2026-03-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0011_alter_developerappaccount_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerappaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='developerappaccount',
            constraint=models.UniqueConstraint(fields=('developer_app', 'account_id'), name='unique_account_per_app'),
        ),
    ]
