# Generated by Django 5.2.7 on 2026-03-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0012_alter_developerappaccount_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='developerappaccount',
            name='unique_account_per_app',
        ),
        migrations.AlterField(
            model_name='developerappaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
