# Generated by Django 5.2.7 on 2026-03-29 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0014_featureconfiguration_template_accounttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureconfiguration',
            name='account',
        ),
        migrations.RemoveField(
            model_name='developerappaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='developerappaccount',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='developerappaccount',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='template',
            name='is_active',
        ),
        migrations.AddField(
            model_name='developerappaccount',
            name='image_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_account', to='platforms.template'),
        ),
        migrations.AddField(
            model_name='developerappaccount',
            name='video_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_account', to='platforms.template'),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='developerappaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Reel')], max_length=10),
        ),
        migrations.CreateModel(
            name='TemplateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='platforms.template')),
            ],
        ),
        migrations.DeleteModel(
            name='AccountTemplate',
        ),
        migrations.DeleteModel(
            name='FeatureConfiguration',
        ),
    ]
