# Generated by Django 5.2.7 on 2026-03-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0015_remove_featureconfiguration_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerappaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
