# Generated by Django 5.2.7 on 2026-03-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0016_developerappaccount_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerappaccount',
            name='created_at',
        ),
    ]
