# Generated by Django 5.2.7 on 2026-03-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0017_remove_developerappaccount_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerappaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
