# Generated by Django 5.2.7 on 2026-03-30 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0018_developerappaccount_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerappaccount',
            name='image_template',
        ),
        migrations.RemoveField(
            model_name='developerappaccount',
            name='video_template',
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('image', 'Image'), ('reel', 'Reel'), ('story', 'Story'), ('video', 'Video')], max_length=10),
        ),
        migrations.CreateModel(
            name='AccountTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_templates', to='platforms.developerappaccount')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.template')),
            ],
            options={
                'unique_together': {('account', 'template_type')},
            },
        ),
        migrations.CreateModel(
            name='AccountTemplateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(max_length=10)),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_configurations', to='platforms.developerappaccount')),
            ],
            options={
                'unique_together': {('account', 'template_type')},
            },
        ),
        migrations.DeleteModel(
            name='TemplateConfiguration',
        ),
    ]
