# Generated by Django 5.2.7 on 2026-02-21 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together={('workspace', 'user')},
        ),
    ]
