# Generated by Django 5.2.7 on 2026-02-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkspaceMember',
        ),
    ]
