# Generated by Django 5.2.7 on 2026-02-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_workspacemember'),
        ('workspaces', '0003_workspaceinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=None, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=255, unique=True)),
                ('temp_data', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_sessions', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
