# Generated by Django 5.2.7 on 2026-02-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_oauthsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthSession',
        ),
    ]
