# Generated by Django 5.2.7 on 2026-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plankey_alter_planquota_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
