# Generated by Django 5.2.7 on 2026-04-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='credits',
            new_name='credit',
        ),
    ]
