# Generated by Django 5.2.7 on 2026-04-16 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_usage_log'),
        ('platforms', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usagelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='account',
            field=models.ForeignKey(blank=True, help_text='The Instagram account that triggered this usage entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='platforms.developerappaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='usagelog',
            unique_together={('user', 'key', 'date', 'account')},
        ),
    ]
