# Generated by Django 5.2.7 on 2026-04-16 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_account_to_usagelog'),
        ('platforms', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usagelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='media_type',
            field=models.CharField(blank=True, choices=[('reel', 'Reel'), ('image', 'Image'), ('story', 'Story'), ('post', 'Post')], help_text='Type of media posted (reel, image, story, post).', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usagelog',
            unique_together={('user', 'key', 'date', 'account', 'media_type')},
        ),
    ]
