# Generated by Django 5.2.7 on 2026-04-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_usagelog_unique_together_usagelog_media_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsageLog',
        ),
    ]
