# Generated by Django 5.2.7 on 2026-04-16 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_delete_usagelog'),
        ('platforms', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('blocked_count', models.IntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, help_text='The Instagram account that triggered this usage entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='platforms.developerappaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'key', 'date', 'account')},
            },
        ),
    ]
