# Generated by Django 5.2.7 on 2026-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_usagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
