# Generated by Django 5.2.7 on 2026-04-19 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_usagelog_last_success_at'),
        ('platforms', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usagelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='credit_from',
            field=models.CharField(default='plan', help_text="Source of credit: 'plan' or 'free'", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='usagelog',
            unique_together={('user', 'key', 'date', 'account', 'credit_from')},
        ),
    ]
