# Generated by Django 5.2.7 on 2026-04-19 09:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_usagelog_unique_together_usagelog_credit_from_and_more'),
        ('platforms', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usagelog',
            unique_together={('user', 'key', 'date', 'account')},
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='credit_from',
        ),
    ]
