# Generated by Django 5.2.7 on 2026-04-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_usagelog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='credit_from_free',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='credit_from_plan',
            field=models.IntegerField(default=0),
        ),
    ]
