# Generated by Django 5.2.7 on 2026-02-21 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform_media_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('views', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('comments_count', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('impressions', models.BigIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('published_at', models.DateTimeField()),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='platforms.platformaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform_comment_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('comment_text', models.TextField()),
                ('is_replied', models.BooleanField(default=False)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_comments', to='platforms.platformaccount')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaPlatformCrosspost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform_media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('master_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossposts', to='media.media')),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossposts', to='platforms.platformaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountAnalyticsDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('followers', models.BigIntegerField(default=0)),
                ('subscribers', models.BigIntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('total_reach', models.BigIntegerField(default=0)),
                ('total_engagement', models.BigIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='platforms.platformaccount')),
            ],
            options={
                'unique_together': {('platform_account', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MediaAnalyticsDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('views', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('impressions', models.BigIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='media.media')),
            ],
            options={
                'unique_together': {('media', 'date')},
            },
        ),
    ]
